### ISSUE TITLE
Builders Wands queing right-click.

### ISSUE THREAD

**Issue by Bucket777** [jadedcat/AS2Configs#16]
Switching away from the builders wand in the hot-bar (I usually mouse-wheel), performs a right-click with the next item.
Edit: AS2 Version:1.1.6

**Comment by samuelroy21** [comment]
this may have been fixed in a more recent version of extra utilities. I'll try it in the current version.

**Comment by samuelroy21** [comment]
this bug has been fixed in later versions of the pack.

**Comment by Bucket777** [comment]
Thanks, I could not test 1.1.8 since I'm using the alternative with the native MC launcher.

**Comment by Bucket777** [comment]
Just tested this with 1.1.8 alternative download. And it is still happening when placing slabs and switching to either slabs or a crescent hammer in the hot-bar.

**Comment by pjfranke** [comment]
This seems to be an error with Extra Utilities, that is as of yet un-fixed even in current versions.  Once a fix is implemented and made available, the next pack update will implement it, barring terrible release timing.  If that, then the next update.
